version: '3'

services:

  shardsvr1_1:
    container_name: shardsvr1_1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017
    ports:
      - 27014:27017
    volumes:
      - shardsvr1_1:/data/db



volumes:
  shardsvr1_1:

